// <auto-generated />
using System;
using HR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Infrastructure.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260408004218_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo",
                            BasicSalary = 8000m,
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 9, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            ContractDate = new DateTime(2015, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Mohamed Ahmed Ismail",
                            Gender = "Male",
                            IsActive = true,
                            NationalId = "29005151234567",
                            Nationality = "Egyptian",
                            Phone = "01012345678",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Address = "اGiza, Doki",
                            BasicSalary = 6500m,
                            BirthDate = new DateTime(1993, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 9, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            ContractDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "sara Mahmoud",
                            Gender = "Female",
                            IsActive = true,
                            NationalId = "29308221234568",
                            Nationality = "Egyptian",
                            Phone = "01123456789",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria",
                            BasicSalary = 12000m,
                            BirthDate = new DateTime(1988, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 8, 30, 0, 0),
                            CheckOutTime = new TimeSpan(0, 16, 30, 0, 0),
                            ContractDate = new DateTime(2012, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Ahmed Khaled Hassan",
                            Gender = "Male",
                            IsActive = true,
                            NationalId = "28801101234569",
                            Nationality = "Egyptian",
                            Phone = "01234567890",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo",
                            BasicSalary = 5000m,
                            BirthDate = new DateTime(1995, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 9, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            ContractDate = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Menna Ibrahim",
                            Gender = "Female",
                            IsActive = true,
                            NationalId = "29503301234560",
                            Nationality = "Egyptian",
                            Phone = "01098765432",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Address = "October",
                            BasicSalary = 9500m,
                            BirthDate = new DateTime(1991, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 9, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            ContractDate = new DateTime(2016, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Omar Yousef",
                            Gender = "Male",
                            IsActive = true,
                            NationalId = "29111051234561",
                            Nationality = "Egyptian",
                            Phone = "01511223344",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Maadi",
                            BasicSalary = 4500m,
                            BirthDate = new DateTime(1997, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 10, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 18, 0, 0, 0),
                            ContractDate = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nourahan Ali",
                            Gender = "Female",
                            IsActive = true,
                            NationalId = "29706181234562",
                            Nationality = "Egyptian",
                            Phone = "01677889900",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Address = "Cairo",
                            BasicSalary = 15000m,
                            BirthDate = new DateTime(1985, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 8, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 16, 0, 0, 0),
                            ContractDate = new DateTime(2010, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Kareem ali",
                            Gender = "Male",
                            IsActive = true,
                            NationalId = "28509251234563",
                            Nationality = "Egyptian",
                            Phone = "01022334455",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Address = "Giza",
                            BasicSalary = 7000m,
                            BirthDate = new DateTime(1992, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInTime = new TimeSpan(0, 9, 0, 0, 0),
                            CheckOutTime = new TimeSpan(0, 17, 0, 0, 0),
                            ContractDate = new DateTime(2019, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Reem Adel",
                            Gender = "Female",
                            IsActive = true,
                            NationalId = "29204121234564",
                            Nationality = "Egyptian",
                            Phone = "01155667788",
                            UpdatedAt = new DateTime(2021, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
